### ISSUE TITLE
After updating python to 3.2.0 , compiling armadillo2 package fails

### ISSUE THREAD

**Issue by elhayra** [robotican/armadillo_2.1#11]
Issue Description
after updating python to 3.2.0 , compiling armadillo2 package fails

Steps To Reproduce The Behavior
update to python 3.2.0 and compile package

Relavent Log Files And Pictures
/usr/local/include/opencv2/flann/saving.h:113:63: error: exception handling disabled, use -fexceptions to enable
throw FLANNException("Invalid index file, cannot read");

**Comment by elhayra** [comment]
add the following line to kinect_registration CMakeLists.txt and recompile:
add_definitions( -fexceptions )
